"""
Form Filler Service - PDF Population with pypdf

Fills official PDF templates (like I-983) with student/employer data.
Uses the field mappings generated by inspect_pdf_fields.py to map
semantic field names to actual PDF form field names.

Key principle: NEVER modify the PDF template structure.
We only fill existing AcroForm fields.
"""

import json
from pathlib import Path
from typing import Optional
from datetime import date

from pypdf import PdfReader, PdfWriter

from app.core.config import TEMPLATES_DIR, DATA_DIR


class FormFiller:
    """
    Service for filling PDF forms using field mappings.
    
    Usage:
        filler = FormFiller()
        output_path = filler.fill_i983(
            student_data={...},
            employer_data={...},
            output_path=Path("output.pdf")
        )
    """
    
    def __init__(
        self,
        template_dir: Optional[Path] = None,
        mappings_path: Optional[Path] = None,
    ):
        """
        Initialize the FormFiller.
        
        Args:
            template_dir: Directory containing PDF templates.
            mappings_path: Path to field_mappings.json.
        """
        self.template_dir = template_dir or TEMPLATES_DIR
        self.mappings_path = mappings_path or (TEMPLATES_DIR / "field_mappings.json")
        
        # Load mappings
        self.field_mappings = self._load_mappings()
        
        # Reverse mapping: semantic_key -> pdf_field_name
        self.reverse_mappings = {v: k for k, v in self.field_mappings.items()}
    
    def _load_mappings(self) -> dict:
        """Load field mappings from JSON file."""
        if not self.mappings_path.exists():
            raise FileNotFoundError(
                f"Field mappings not found at {self.mappings_path}. "
                "Run scripts/inspect_pdf_fields.py first."
            )
        
        with open(self.mappings_path, "r") as f:
            return json.load(f)
    
    def get_pdf_field_name(self, semantic_key: str) -> Optional[str]:
        """
        Get the PDF field name for a semantic key.
        
        Args:
            semantic_key: The human-readable field name (e.g., "Student_Name")
            
        Returns:
            The actual PDF field name, or None if not found.
        """
        return self.field_mappings.get(semantic_key)
    
    def prepare_i983_data(
        self,
        student_data: dict,
        employer_data: dict,
        training_plan: dict,
    ) -> dict:
        """
        Prepare data for I-983 form filling.
        
        Maps our internal data structure to I-983 semantic field names.
        
        Args:
            student_data: Dict with student information.
            employer_data: Dict with employer information.
            training_plan: Dict with training plan details.
            
        Returns:
            Dict mapping semantic field names to values.
        """
        today = date.today().strftime("%m-%d-%Y")
        
        # Map student data
        data = {
            # Section 1 - Student Information
            "Student_Name_(Surname,_Given_Name)": 
                f"{student_data.get('last_name', '')}, {student_data.get('first_name', '')}",
            "Student_SEVIS_ID_Number": student_data.get("sevis_id", ""),
            "Student_Email_Address": student_data.get("email", ""),
            
            # Degree Information
            "Name_of_School_Where_Stem_Degree_Was_Earned": 
                student_data.get("school_name", ""),
            "Level/Type_of_Qualifying_Degree": student_data.get("degree_level", ""),
            "Degree_Awarded_Date(mm-dd-yyyy)": student_data.get("graduation_date", ""),
            "Qualifying_Major_and_Classification_of_Instructional_Programs_(CIP)_Code": 
                student_data.get("major_cip", ""),
            
            # OPT Information
            "STEM_OPT_Requested_From_(mm-dd-yyyy)": student_data.get("opt_start", ""),
            "STEM_OPT_Requested_To_(mm-dd-yyyy)": student_data.get("opt_end", ""),
            "Employment_Authorization_Number": student_data.get("ead_number", ""),
            
            # Section 2 - Student Certification
            "Printed_Name_of_Student_SECTION_2_STUDENT_CERTIFICATION": 
                f"{student_data.get('first_name', '')} {student_data.get('last_name', '')}",
            "Date_(mm-dd-yyyy)_SECTION_2_STUDENT_CERTIFICATION": today,
            
            # Employer Information
            "Employer_Name": employer_data.get("company_name", ""),
            "Employer_Street_Address": employer_data.get("street", ""),
            "Employer_City": employer_data.get("city", ""),
            "Employer_State": employer_data.get("state", ""),
            "Employer_Zip_Code": employer_data.get("zip", ""),
            "Employer_ID_Number_(EIN)": employer_data.get("ein", ""),
            "Employer_Website_URL": employer_data.get("website", ""),
            "Number_of_Full-Time_Employees_in_U.S.": 
                str(employer_data.get("employee_count", "")),
            "North_American_Industry_Classification_System_(NAICS)_COde": 
                employer_data.get("naics_code", ""),
            
            # Section 4 - Employer Certification
            "Date_(mm-dd-yyyy)_SECTION_4_EMPLOYER_CERTIFICATION": today,
            
            # Training Plan (Section 5)
            "Start_Date_of_Employment_(mm-dd-yyyy)": 
                training_plan.get("start_date", ""),
            "OPT_Hours_Per_Week(must_be_at_least_20_hours/week)": 
                str(training_plan.get("hours_per_week", "40")),
            "Salary_Amount_and_Frequency": 
                training_plan.get("salary", ""),
            
            # Site Information
            "Site_Name_SUBSECTION_EMPLOYER_SITE_INFORMATION_SECTION_5_TRAINING_PLAN_FOR_STEM_OPT_STUDENTS_(Completed_by_Student_and_Employer)": 
                training_plan.get("site_name", employer_data.get("company_name", "")),
            "Site_Address_(Street,_City,_State,_ZIP)_SUBSECTION_EMPLOYER_SITE_INFORMATION_SECTION_5_TRAINING_PLAN_FOR_STEM_OPT_STUDENTS_(Completed_by_Student_and_Employer)": 
                training_plan.get("site_address", ""),
            
            # Goals and Assessments
            "Goals_and_Objectives:_Describe_how_the_assignment(s)_with_the_employer_will_help_the_student_achieve_his_or_her_specific_objectives_for_work-based_learning_related_to_his_or_her_STEM_degree._The_description_must_both_specify_the_student's_goals_regarding_specific_knowledge,_skills,_or_techniques_as_well_as_the_means_by_which_they_will_be_achieved": 
                training_plan.get("goals", ""),
            "Student_Role:_Describe_the_student's_role_with_the_employer_and_how_that_role_is_directly_related_to_enhancing_the_student's_knowledge_obtained_through_his_or_her_qualifying_STEM_degree": 
                training_plan.get("role_description", ""),
            "Employer_Oversight:_Explain_how_the_employer_provides_oversight_and_supervision_of_individuals_filling_positions_such_as_that_being_filled_by_the_named_F-1_student._If_the_employer_has_a_training_program_or_related_policy_in_place_that_controls_such_oversight_and_supervision,_please_describe.": 
                training_plan.get("oversight", ""),
            "Measures_and_Assessments:_Explain_how_the_employer_measures_and_confirms_whether_individuals_filling_positions_such_as_that_being_filled_by_the_named_F-1_student_are_acquiring_new_knowledge_and_skills._If_the_employer_has_a_training_program_or_related_policy_in_place_that_controls_such_measures_and_assessments,_please_describe.": 
                training_plan.get("assessments", ""),
            
            # Supervisor Information
            "Name_of_Official_SUBSECTION_EMPLOYER_SITE_INFORMATION_SECTION_5_TRAINING_PLAN_FOR_STEM_OPT_STUDENTS_(Completed_by_Student_and_Employer)": 
                training_plan.get("supervisor_name", ""),
            "Official's_Title_SUBSECTION_EMPLOYER_SITE_INFORMATION_SECTION_5_TRAINING_PLAN_FOR_STEM_OPT_STUDENTS_(Completed_by_Student_and_Employer)": 
                training_plan.get("supervisor_title", ""),
            "Official's_Email_SUBSECTION_EMPLOYER_SITE_INFORMATION_SECTION_5_TRAINING_PLAN_FOR_STEM_OPT_STUDENTS_(Completed_by_Student_and_Employer)": 
                training_plan.get("supervisor_email", ""),
            "Official's_Phone_Number_SUBSECTION_EMPLOYER_SITE_INFORMATION_SECTION_5_TRAINING_PLAN_FOR_STEM_OPT_STUDENTS_(Completed_by_Student_and_Employer)": 
                training_plan.get("supervisor_phone", ""),
        }
        
        # Handle radio buttons
        if student_data.get("based_on_prior_degree"):
            data["Based_on_Prior_Degree_(Yes/No)"] = "/Yes"
        else:
            data["Based_on_Prior_Degree_(Yes/No)"] = "/No"
        
        return data
    
    def fill_pdf(
        self,
        template_path: Path,
        field_values: dict,
        output_path: Path,
    ) -> Path:
        """
        Fill a PDF template with provided values.
        
        Args:
            template_path: Path to the PDF template.
            field_values: Dict mapping semantic field names to values.
            output_path: Path for the output PDF.
            
        Returns:
            Path to the generated PDF.
        """
        # Read the template
        reader = PdfReader(template_path)
        writer = PdfWriter()
        
        # Copy pages
        for page in reader.pages:
            writer.add_page(page)
        
        # Convert semantic keys to PDF field names
        pdf_field_values = {}
        for semantic_key, value in field_values.items():
            pdf_field = self.get_pdf_field_name(semantic_key)
            if pdf_field:
                pdf_field_values[pdf_field] = value
            else:
                # Try using the key directly (might already be a PDF field name)
                pdf_field_values[semantic_key] = value
        
        # Fill fields
        writer.update_page_form_field_values(
            writer.pages[0],
            pdf_field_values,
        )
        
        # Handle multi-page forms
        if len(writer.pages) > 1:
            for i, page in enumerate(writer.pages[1:], 1):
                try:
                    writer.update_page_form_field_values(page, pdf_field_values)
                except Exception:
                    pass  # Some pages may not have form fields
        
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Write output
        with open(output_path, "wb") as f:
            writer.write(f)
        
        return output_path
    
    def fill_i983(
        self,
        student_data: dict,
        employer_data: dict,
        training_plan: dict,
        output_path: Optional[Path] = None,
    ) -> Path:
        """
        Fill an I-983 form with student and employer data.
        
        This is the main entry point for I-983 generation.
        
        Args:
            student_data: Dictionary with student information.
            employer_data: Dictionary with employer information.
            training_plan: Dictionary with training plan details.
            output_path: Optional path for output. Auto-generated if not provided.
            
        Returns:
            Path to the generated PDF.
        """
        # Find template
        template_candidates = [
            self.template_dir / "i983_template.pdf",
            self.template_dir / "I-983.pdf",
            self.template_dir / "i983.pdf",
        ]
        
        template_path = None
        for candidate in template_candidates:
            if candidate.exists():
                template_path = candidate
                break
        
        if not template_path:
            raise FileNotFoundError(
                f"I-983 template not found in {self.template_dir}. "
                "Please add i983_template.pdf to the templates directory."
            )
        
        # Prepare data
        field_values = self.prepare_i983_data(
            student_data=student_data,
            employer_data=employer_data,
            training_plan=training_plan,
        )
        
        # Generate output path
        if output_path is None:
            output_dir = DATA_DIR / "generated" / "forms"
            output_dir.mkdir(parents=True, exist_ok=True)
            
            student_name = student_data.get("last_name", "unknown")
            timestamp = date.today().strftime("%Y%m%d")
            output_path = output_dir / f"I-983_{student_name}_{timestamp}.pdf"
        
        # Fill and return
        return self.fill_pdf(
            template_path=template_path,
            field_values=field_values,
            output_path=output_path,
        )


def get_form_filler() -> FormFiller:
    """Get a configured FormFiller instance."""
    return FormFiller()
